---
apiVersion: v1
kind: Namespace
metadata:
  name: nwns
  labels: 
    app: nwapp
    version: v1

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nwapp-cm
  labels:
    app: nwapp

data:
  DB_USER: root
  DB_HOST: nwdb-svc.nwns.svc.cluster.local # FQDN

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nw-deploy
  labels:
    app: nwapp

spec:
  replicas: 3
  selector:
    matchLabels:
      app: nwapp-pod

  template:
    metadata:
      name: nwapp-pod
      labels: 
        app: nwapp-pod
    spec:
      containers:
      - name: nwapp-container
        image: chukmunnlee/my-nwapp:v1
        imagePullPolicy: IfNotPresent
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nw-secret
              key: MYSQL_ROOT_PASSWORD 
        - name: INSTANCE_IP_ADDRESS
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        envFrom:
          - configMapRef:
              name: nwapp-cm
        ports:
        - name: nwapp-port
          containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: nwapp-svc
  labels: 
    app: nwapp

spec:
  type: LoadBalancer
  selector:
    app: nwapp-pod
  ports:
  - name: nwapp-svc-port
    port: 80
    targetPort: nwapp-port