---
apiVersion: v1
kind: Secret
metadata:
  name: nw-secret
  labels:
    app: nwdb
  
data:
  MYSQL_ROOT_PASSWORD: Y2hhbmdlaXQ=

---
apiVersion: apps/v1
kind: Deployment

metadata:
   name: nwdb-deploy
   labels:
      app: nwdb

spec:
   replicas: 1
   selector:
      matchLabels:
         app: nwdb
   minReadySeconds: 30
   template:
      metadata:
         name: nwdb-pod
         labels:
            app: nwdb
      spec:
         containers:
         - name: nwdb-container
           image: chukmunnlee/my-nwdb:v3
           envFrom:
           - secretRef:
              name: nw-secret
           imagePullPolicy: IfNotPresent
           ports:
           - name: nwdb-port
             containerPort: 3306

---
apiVersion: v1
kind: Service
metadata:
   name: nwdb-svc
   labels:
      app: nwdb

spec:
   type: ClusterIP
   selector:
      app: nwdb
   ports:
   - port: 3306
     targetPort: nwdb-port