---
apiVersion: v1
kind: Secret
metadata:
  name: nw-secret
  labels:
    app: nwdb
  
data:
  MYSQL_ROOT_PASSWORD: Y2hhbmdlaXQ=

---
apiVersion: apps/v1
kind: Deployment

metadata:
   name: nwdb-deploy
   labels:
      app: nwdb

spec:
   replicas: 1
   selector:
      matchLabels:
         app: nwdb
   minReadySeconds: 30
   template:
      metadata:
         name: nwdb-pod
         labels:
            app: nwdb
      spec:
         volumes:
         - name: nwdb-vol
           persistentVolumeClaim:
               claimName: nwdb-pvc
         - name: share-dir
           emptyDir: {}

         initContainers:
         - name: busybox
           image: busybox
           volumeMounts:
           - name: nwdb-vol
             mountPath: /scrub
           - name: share-dir
             mountPath: /tmp/share
           command:
           - /bin/sh
           - -c 
           - "test -e /scrub && rm -rf /scrub/..?* /scrub/.[!.]* /scrub/*  && test -z \"$(ls -A /scrub)\" || exit 1" 
         
         containers:
         - name: nwdb-container
           image: chukmunnlee/my-nwdb:v3
           envFrom:
           - secretRef:
              name: nw-secret
           imagePullPolicy: IfNotPresent
           ports:
           - name: nwdb-port
             containerPort: 3306

           volumeMounts:
           - name: nwdb-vol
             mountPath: /var/lib/mysql

---
apiVersion: v1
kind: Service
metadata:
   name: nwdb-svc
   labels:
      app: nwdb

spec:
   type: ClusterIP
   selector:
      app: nwdb
   ports:
   - port: 3306
     targetPort: nwdb-port